# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komisionet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emertimi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='KomisionetV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komisioni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Komisionet')),
            ],
        ),
        migrations.CreateModel(
            name='Vlersues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='komisionetv',
            name='vlersuesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vlersues'),
        ),
    ]
