# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komisionet',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vlersues',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
