# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190626_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopusKatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopusid', models.CharField(max_length=250)),
                ('pubmedid', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('affiliation', models.CharField(max_length=250)),
                ('citattion_count', models.CharField(max_length=250)),
            ],
        ),
    ]
