# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scopuskatalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopuskatalog',
            old_name='citattion_count',
            new_name='citation_count',
        ),
    ]
