# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190711_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopuskatalog',
            name='affiliation',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scopuskatalog',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scopuskatalog',
            name='citation_count',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scopuskatalog',
            name='pubmedid',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='scopuskatalog',
            name='scopusid',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
