# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190711_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopuskatalog',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scopuskatalog',
            name='issn',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scopuskatalog',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
