# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190717_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopuskatalog',
            name='journal',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
